### ISSUE TITLE
PyPI package for version 0.3.17 is missing pyyaml dependency

### ISSUE THREAD

**Issue by LordFckHelmchen** [elisiariocouto/jsonschema-markdown#21]
Hey @elisiariocouto,

Just attempted to use your nice tool! However in the current version, there is a missing dependency to pyyaml.

The package uploaded to [PyPI](https://files.pythonhosted.org/packages/44/3d/a225fba86dbf682fbf21309aea62f5c8803aac93f00df040e05e8f1259f6/jsonschema_markdown-0.3.17-py3-none-any.whl) has the following METADATA dependency block

```text
...
Requires-Dist: click (>=8.1.7,<9.0.0)
Requires-Dist: jsonref (>=1.1.0,<2.0.0)
Requires-Dist: loguru (>=0.7.2,<0.8.0)
...
```

But instead it should be 

```text
Requires-Dist: click (>=8.1.7,<9.0.0)
Requires-Dist: jsonref (>=1.1.0,<2.0.0)
Requires-Dist: loguru (>=0.7.2,<0.8.0)
Requires-Dist: pyyaml (>=6.0.2,<7.0.0)
```

Just checked-out the main branch and built with poetry - there the package is correctly built and includes the dependency. Maybe just retrigger the release workflow?

**Comment by elisiariocouto** [comment]
Hello @LordFckHelmchen

Thank you for the heads up, forgot to release it 😬
Just released 0.3.18 with the missing pyyaml dependency.
