### ISSUE TITLE
additionalProperties on object property doesn't translate into the right type

### ISSUE THREAD

**Issue by Omri-Ben-Yair** [elisiariocouto/jsonschema-markdown#22]
When defining a field as object with additionalProperties, the type being generated is the type of the additionalProperties clause, which is inccorect.

For example for the following JsonSchema:

```
{
   "title": "Model1",
   "description": "Description",
   "type": "object",
   "properties": {
      "tags": {
         "title": "Tags",
         "description": "Tags",
         "type": "object",
         "additionalProperties": {
            "type": "string"
         }
      }
   }
}
```

I would expect the md file to be:
| Property | Type | Required | Possible Values | Deprecated | Default | Description |
| -------- | ---- | -------- | --------------- | ---------- | ------- | ----------- |
| tags | `object` |  | object|  |  |Tags |

But in reality it's:
| Property | Type | Required | Possible Values | Deprecated | Default | Description |
| -------- | ---- | -------- | --------------- | ---------- | ------- | ----------- |
| tags | `string` |  | string|  |  | Tags |

The code inside markdown.py:

```
elif "additionalProperties" in property_details and not isinstance(
    property_details["additionalProperties"], bool
):
    new_type = property_details["additionalProperties"].get("type")
    return new_type, new_type
```
        
Should be changed to:

```
elif "additionalProperties" in property_details and not isinstance(
    property_details["additionalProperties"], bool
):
    return property_type, property_type
```

**Reasoning**:
The additionalProperties should not change an object type to another type, it only restrict the object type properties to be on the type mentioned inside the additionalProperties attribute.

[json-schema#additionalProperties](https://json-schema.org/understanding-json-schema/reference/object#additionalproperties)        

**Another suggestion**:
The best would be if we can present in some way that the object properties are of type `string`

**Comment by Omri-Ben-Yair** [comment]
Woopsy, wasn't using the latest version

**Comment by elisiariocouto** [comment]
No problem, thank you for your feedback anyway :)
